name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Compile source files and create distribution zip
  build:
    runs-on: ubuntu-latest
# TOOD: Use matrix testing after we added some actual unit testing
#    strategy:
#      matrix:
#        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Reconfigure git to use HTTP authentication
      run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
    - name: Use Node.js 12.x #${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x #${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Compile source files
      run: |
        chmod +x dist.sh
        ./dist.sh
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.tar.gz
